### PR TITLE
Update application version to v1.8.9.1

### PR DESCRIPTION
**Pull request by fxusyd**

### CODE REVIEW

**Comment by anzhao** [comment]
Hi Fang, how about update to v1.8.9.2?

**Comment by fxusyd** [comment]
Yes, it’s coming soon.

From: An Zhao ***@***.***>
Date: Tuesday, 12 December 2023 at 6:00 pm
To: Australian-Imaging-Service/charts ***@***.***>
Cc: Fang Xu ***@***.***>, State change ***@***.***>
Subject: Re: [Australian-Imaging-Service/charts] Update application version to v1.8.9.1 (PR #133)

Hi Fang, how about update to v1.8.9.2?

**Comment by anzhao** [comment]
Excellent, thank you Fang.

**Comment by fxusyd** [comment]
Hi An,

Chart uses v1.8.9.2 by default now.

Cheers,
Fang

From: An Zhao ***@***.***>
Date: Wednesday, 13 December 2023 at 8:42 am
To: Australian-Imaging-Service/charts ***@***.***>
Cc: Fang Xu ***@***.***>, State change ***@***.***>
Subject: Re: [Australian-Imaging-Service/charts] Update application version to v1.8.9.1 (PR #133)

Excellent, thank you Fang.

**Comment by anzhao** [comment]
Hi Fang, thank you for let me know.

**Pull request merged**
